# Generated by Django 5.1.6 on 2025-03-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='accounts/images/%Y/%m/%d/%h/%M/'),
        ),
    ]
