# Generated by Django 5.1.6 on 2025-03-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='media/accounts/images/%Y/%m/%d/'),
        ),
    ]
